### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by arjansingh**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/dollarshaveclub/ember-route-layers/pull/23" target="_blank">ReviewNinja

**Comment by arjansingh** [comment]
@blimmer updating the version and publishing.

**Comment by arjansingh** [comment]
+1

**Comment by arjansingh** [comment]
@blimmer 2.4.3 is published

**Comment by blimmer** [comment]
Thanks!

**Pull request merged**
